/**
 * Tipos JSX de las etiquetas de nx32-elements para SolidJS (`prop:`, `attr:`, `bool:`, `on:`). Solo tipos:
 * en ejecución este módulo está vacío. Van juntos porque TypeScript funde las interfaces de
 * `solid-js` y una misma prop (`labels`, `items`) tiene que tener un solo tipo.
 */
import type { NxButton } from "../components/button/button";
import type { ButtonLabels, ButtonVariant, DoneDetail, LogMode } from "../components/button/types";
import type { NxSelect } from "../components/select/select";
import type { SelectChangeDetail, SelectField, SelectLabels, SelectOption } from "../components/select/types";
import type { NxAiAnswer } from "../components/ai/ai-answer";
import type { AiActionDetail, AiDoneDetail, AiEvent, AiFeedbackDetail, AiLabels } from "../components/ai/types";
import type { NxDocCapture } from "../components/capture/doc-capture";
import type { CaptureEvent, CaptureLabels, CaptureSchemaItem, CaptureSubmitDetail, CaptureValues } from "../components/capture/types";
import type { NxGrid } from "../components/grid/grid";
import type { GridAction, GridActionDetail, GridChange, GridChangeSource, GridColumn, GridErrorDetail, GridExportDetail, GridFilter, GridLabels, GridPreset, GridRow, GridSavedView, GridSort, GridView } from "../components/grid/types";
import type { NxDialog } from "../components/dialog/dialog";
import type { CloseReason, DialogAction, DialogActionDetail, DialogCloseDetail, DialogLabels, DialogMode, DialogNavDetail, DialogSize } from "../components/dialog/types";
import type { NxBadge } from "../components/badge/badge";
import type { NxNotice } from "../components/notice/notice";
import type { NoticeActionDetail } from "../components/notice/types";
import type { NxFields } from "../components/fields/fields";
import type { FieldItem, FieldsActionDetail, FieldsLabels, FieldsVariant } from "../components/fields/types";
import type { NxTabs } from "../components/tabs/tabs";
import type { TabItem, TabsChangeDetail, TabsLabels } from "../components/tabs/types";
import type { NxBreadcrumb } from "../components/breadcrumb/breadcrumb";
import type { BreadcrumbExpandDetail, BreadcrumbItem, BreadcrumbLabels, BreadcrumbNavigateDetail } from "../components/breadcrumb/types";
import type { NxOrg } from "../components/org/org";
import type { OrgContact, OrgFocusDetail, OrgLabels, OrgMetric, OrgPerson, OrgUnit, OrgView } from "../components/org/types";
import type { NxAgent } from "../components/agent/agent";
import type { AgentLabels, AgentToolDetail, AguiContext, AguiEvent, AguiTool } from "../components/agent/types";
import type { NxCommand } from "../components/command/command";
import type { CommandItem, CommandLabels, CommandSelectDetail } from "../components/command/types";
import type { NxExplain } from "../components/explain/explain";
import type { ExplainEvent, ExplainLabels } from "../components/explain/types";
import type { NxInbox } from "../components/inbox/inbox";
import type { InboxDecisionDetail, InboxItem, InboxLabels } from "../components/inbox/types";
import type { NxSurvey } from "../components/survey/survey";
import type { SurveyAnswers, SurveyLabels, SurveyQuestionInput, SurveyResults, SurveySubmitDetail } from "../components/survey/types";
import type { NxNumber } from "../components/number/number";
import type { NumberAlign, NumberChangeDetail, NumberFormat, NumberLabels } from "../components/number/types";
import type { NxKanban } from "../components/kanban/kanban";
import type { KanbanCard, KanbanColumn, KanbanLabels, KanbanMoveDetail } from "../components/kanban/types";
import type { NxHistory } from "../components/history/history";
import type { HistoryActor, HistoryCommitDetail, HistoryEvent, HistoryField, HistoryLabels, HistoryRevertDetail, HistoryValue } from "../components/history/types";
import type { NxPasteFill } from "../components/paste-fill/paste-fill";
import type { PasteFieldInput, PasteFillDoneDetail, PasteFillLabels } from "../components/paste-fill/types";
import type { NxPresence } from "../components/presence/presence";
import type { PresenceEvent, PresenceLabels, PresenceState, PresenceUser } from "../components/presence/types";
import type { NxWhatIf } from "../components/what-if/what-if";
import type { WhatIfChangeDetail, WhatIfComputeDetail, WhatIfInput, WhatIfLabels, WhatIfMetric, WhatIfSaveDetail, WhatIfScenario, WhatIfSeries, WhatIfValues } from "../components/what-if/types";
import type { NxTrend } from "../components/trend/trend";
import type { TrendAnomaly, TrendFormat, TrendKind, TrendLabels, TrendSeries, TrendWhyDetail } from "../components/trend/types";
import type { NxScan } from "../components/scan/scan";
import type { ScanCountDetail, ScanDetail, ScanItem, ScanLabels, ScanMode, ScanProblem, ScanWedge } from "../components/scan/types";
import type { NxSync } from "../components/sync/sync";
import type { SyncChangeDetail, SyncField, SyncLabels, SyncOp } from "../components/sync/types";
import type { NxDateRange } from "../components/date-range/date-range";
import type { DateRangeChangeDetail, DateRangeCompare, DateRangeLabels, DateRangePresetInput, DateRangeValue } from "../components/date-range/types";
import type { NxImport } from "../components/import/import";
import type { ImportColumnInput, ImportDoneDetail, ImportErrorDetail, ImportLabels, ImportMappedDetail, ImportParsedDetail, ImportState } from "../components/import/types";
import type { NxKeytips } from "../components/keytips/keytips";
import type { KeytipAssignment, KeytipDetail, KeytipsLabels } from "../components/keytips/types";
import type { NxGuard } from "../components/guard/guard";
import type { GuardFields, GuardFinding, GuardLabels, GuardMode } from "../components/guard/types";
import type { NxHandoff } from "../components/handoff/handoff";
import type { HandoffDoneDetail, HandoffItemDetail, HandoffKind, HandoffLabels, HandoffPhoneLabels, HandoffSide, HandoffState } from "../components/handoff/types";
import type { NxAward } from "../components/award/award";
import type { AwardAdviseDetail, AwardChangeDetail, AwardChoice, AwardCriterion, AwardEvent, AwardFilter, AwardItem, AwardLabels, AwardLens, AwardQuote, AwardSubmitDetail, AwardSupplier } from "../components/award/types";
import type { NxAccount } from "../components/account/account";
import type { AccountItem, AccountLabels, AccountLocale, AccountLogoutDetail, AccountPalette, AccountPerson, AccountSession, AccountStatus, AccountStatusDetail, AccountSwitchDetail, AccountTenant, AccountThemeDetail, AccountUser, AccountViewAsDetail } from "../components/account/types";
import type { NxCards } from "../components/cards/cards";
import type { CardsAction, CardsActionDetail, CardsField, CardsLabels, CardsLayout, CardsLevel, CardsOpenDetail, CardsRow } from "../components/cards/types";
import type { NxLauncher } from "../components/launcher/launcher";
import type { LauncherItem, LauncherLabels, LauncherProgress, LauncherSelectDetail, LauncherSignal, LauncherTone, LauncherView } from "../components/launcher/types";
import type { NxPrint } from "../components/print/print";
import type { PrintLabels, PrintOrientation, PrintPaginateDetail, PrintZoom } from "../components/print/types";
import type { NxSignature } from "../components/signature/signature";
import type { SignatureDoneDetail, SignatureFormat, SignatureLabels, SignatureMeta, SignatureValue } from "../components/signature/types";
import type { NxPlanner } from "../components/planner/planner";
import type { PlannerBooking, PlannerChangeDetail, PlannerCreateDetail, PlannerDeleteDetail, PlannerLabels, PlannerRangeDetail, PlannerResource, PlannerView } from "../components/planner/types";
import type { NxReview } from "../components/review/review";
import type { ReviewChange, ReviewConfirmDetail, ReviewDirtyDetail, ReviewLabels, ReviewMode, ReviewOpenDetail } from "../components/review/types";
import type { NxVoice } from "../components/voice/voice";
import type { VoiceEndDetail, VoiceEngine, VoiceErrorDetail, VoiceLabels, VoiceLayout, VoiceTextDetail } from "../components/voice/types";
import type { NxThread } from "../components/thread/thread";
import type { ThreadComment, ThreadErrorDetail, ThreadLabels, ThreadMentionDetail, ThreadPostDetail, ThreadRef, ThreadUser } from "../components/thread/types";
import type { NxChecklist } from "../components/checklist/checklist";
import type { ChecklistSequence } from "../components/checklist/logic";
import type { ChecklistChangeDetail, ChecklistCompleteDetail, ChecklistErrorDetail, ChecklistLabels, ChecklistMode, ChecklistOpenDetail, ChecklistPerson, ChecklistState, ChecklistStep, ChecklistSummaryItem } from "../components/checklist/types";
import type { NxRecurrence } from "../components/recurrence/recurrence";
import type { RecurrenceChangeDetail, RecurrenceErrorDetail, RecurrenceHolidayMode, RecurrenceLabels, RecurrenceRule, RecurrenceValue, RecurrenceValueFormat } from "../components/recurrence/types";
import type { NxJobs } from "../components/jobs/jobs";
import type { Job, JobEvent, JobResult, JobSpec, JobStatus, JobsErrorDetail, JobsLabels } from "../components/jobs/types";
import type { NxSidemenu } from "../components/sidemenu/sidemenu";
import type { MenuItem, OpenChangeDetail, SelectDetail, SidemenuLabels, ToggleDetail } from "../components/sidemenu/types";

export type GridFilterDetail = { filters: GridFilter[]; sort: GridSort | null; groupBy: string; search: string; count: number };

declare module "solid-js" {
  namespace JSX {
    interface ExplicitProperties {
      steps: ChecklistStep[] | undefined;
      state: unknown;
      sequential: ChecklistSequence | undefined;
      anchors: string[] | undefined;
      refPatterns: string[] | undefined;
      comments: ThreadComment[] | undefined;
      initial: Record<string, unknown> | null | undefined;
      resources: PlannerResource[] | undefined;
      bookings: PlannerBooking[] | undefined;
      workdays: number[] | undefined;
      holidays: string[] | undefined;
      query: string | undefined;
      layout: CardsLayout | null | undefined;
      actions: CardsAction[] | DialogAction[] | GridAction[] | undefined;
      suppliers: AwardSupplier[] | undefined;
      quotes: AwardQuote[] | undefined;
      criteria: AwardCriterion[] | undefined;
      advice: AwardEvent[] | undefined;
      choices: AwardChoice[] | undefined;
      excluded: string[] | undefined;
      reasons: string[] | undefined;
      weights: Record<string, number> | undefined;
      filter: AwardFilter | undefined;
      formats: string[] | undefined;
      anomalies: TrendAnomaly[] | undefined;
      values: WhatIfValues | undefined;
      scenarios: WhatIfScenario[] | undefined;
      series: WhatIfSeries[] | TrendSeries[] | undefined;
      outputs: WhatIfMetric[] | undefined;
      inputs: WhatIfInput[] | undefined;
      me: PresenceUser | ChecklistPerson | null | undefined;
      items: MenuItem[] | CommandItem[] | InboxItem[] | ScanItem[] | AwardItem[] | AccountItem[] | LauncherItem[] | ChecklistSummaryItem[] | FieldItem[] | BreadcrumbItem[] | null | undefined;
      tabs: TabItem[] | null | undefined;
      units: OrgUnit[] | null | undefined;
      people: OrgPerson[] | null | undefined;
      contacts: OrgContact[] | null | undefined;
      metrics: OrgMetric[] | null | undefined;
      errors: Record<string, string> | undefined;
      labels: Partial<SidemenuLabels> | Partial<ButtonLabels> | Partial<SelectLabels> | Partial<AiLabels> | Partial<CaptureLabels> | Partial<GridLabels> | Partial<DialogLabels> | Partial<AgentLabels> | Partial<CommandLabels> | Partial<ExplainLabels> | Partial<InboxLabels> | Partial<SurveyLabels> | Partial<NumberLabels> | Partial<KanbanLabels> | Partial<HistoryLabels> | Partial<DateRangeLabels> | Partial<PasteFillLabels> | Partial<PresenceLabels> | Partial<WhatIfLabels> | Partial<TrendLabels> | Partial<ScanLabels> | Partial<SyncLabels> | Partial<ImportLabels> | Partial<KeytipsLabels> | Partial<GuardLabels> | Partial<HandoffLabels & HandoffPhoneLabels> | Partial<AwardLabels> | Partial<AccountLabels> | Partial<LauncherLabels> | Partial<CardsLabels> | Partial<PrintLabels> | Partial<SignatureLabels> | Partial<PlannerLabels> | Partial<ReviewLabels> | Partial<VoiceLabels> | Partial<ThreadLabels> | Partial<ChecklistLabels> | Partial<RecurrenceLabels> | Partial<JobsLabels> | Partial<FieldsLabels> | Partial<TabsLabels> | Partial<BreadcrumbLabels> | Partial<OrgLabels> | undefined;
      schema: CaptureSchemaItem[] | undefined;
      suggestions: string[] | undefined;
      context: unknown;
      progress: number | null | undefined;
      options: SelectOption[];
      fields: SelectField[] | HistoryField[] | PasteFieldInput[] | SyncField[] | GuardFields | CardsField[] | undefined;
      record: Record<string, unknown> | undefined;
      events: HistoryEvent[] | undefined;
      user: HistoryActor | AccountUser | null | undefined;
      tenants: AccountTenant[] | undefined;
      palettes: (string | AccountPalette)[] | undefined;
      locales: AccountLocale[] | undefined;
      session: AccountSession | null | undefined;
      viewAs: AccountPerson | null | undefined;
      value: string | string[] | number | DateRangeValue | SignatureValue | null | undefined;
      // Los atajos del selector de fechas y los de la tabla: la misma propiedad en dos componentes.
      presets: DateRangePresetInput[] | GridPreset[] | undefined;
      selection: SelectOption[] | undefined;
      columns: GridColumn[] | KanbanColumn[] | ImportColumnInput[];
      cards: KanbanCard[] | undefined;
      rows: GridRow[] | CardsRow[] | undefined;
      filters: GridFilter[] | undefined;
      sort: GridSort | null | undefined;
      search: string | undefined;
      view: Partial<GridView> | undefined;
      views: GridSavedView[] | undefined;
      selected: string[] | undefined;
      active: string | null | undefined;
      dirty: boolean | undefined;
      tools: AguiTool[] | undefined;
      explanation: ExplainEvent[] | null | undefined;
      questions: SurveyQuestionInput[] | undefined;
      answers: SurveyAnswers | undefined;
      results: SurveyResults | null | undefined;
    }
    interface ExplicitAttributes {
      tone: string | undefined;
      text: string | undefined;
      "action-href": string | undefined;
      /** `<nx-button href>`: el botón como enlace. */
      href: string | undefined;
      nav: string | undefined;
      badge: string | undefined;
      "badge-tone": string | undefined;
      avatar: string | undefined;
      recent: string | undefined;
      "holidays-mode": "add" | "replace" | undefined;
      count: string | undefined;
      record: string | undefined;
      poll: string | undefined;
      presence: string | undefined;
      "people-source": string | undefined;
      "refs-source": string | undefined;
      engine: VoiceEngine | undefined;
      "max-seconds": string | undefined;
      silence: string | undefined;
      commands: "false" | undefined;
      threshold: string | undefined;
      "max-silent": string | undefined;
      empty: "notice" | undefined;
      rebase: "false" | undefined;
      view: PlannerView | OrgView | undefined;
      me: string | undefined;
      metric: string | undefined;
      date: string | undefined;
      snap: string | undefined;
      hours: string | undefined;
      summary: string | undefined;
      document: string | undefined;
      handoff: string | undefined;
      "value-format": SignatureFormat | RecurrenceValueFormat | undefined;
      "pen-color": string | undefined;
      orientation: PrintOrientation | undefined;
      margin: string | undefined;
      zoom: string | undefined;
      toolbar: "false" | undefined;
      level: CardsLevel | undefined;
      group: string | undefined;
      sort: string | undefined;
      columns: string | undefined;
      "heading-level": string | undefined;
      scenario: string | undefined;
      lens: AwardLens | undefined;
      side: HandoffSide | undefined;
      session: string | undefined;
      token: string | undefined;
      scope: string | undefined;
      key: string | undefined;
      batch: string | undefined;
      accept: string | undefined;
      "max-size": string | undefined;
      memory: string | undefined;
      ping: string | undefined;
      wedge: ScanWedge | undefined;
      "explain-endpoint": string | undefined;
      "children-endpoint": string | undefined;
      detect: string | undefined;
      kind: TrendKind | HandoffKind | undefined;
      debounce: string | undefined;
      idle: string | undefined;
      channel: string | undefined;
      active: string | undefined;
      label: string | undefined;
      icon: string | undefined;
      variant: ButtonVariant | FieldsVariant | undefined;
      type: "button" | "submit" | "reset" | undefined;
      "log-mode": LogMode | undefined;
      stream: string | undefined;
      method: string | undefined;
      placeholder: string | undefined;
      source: string | undefined;
      name: string | undefined;
      value: string | undefined;
      endpoint: string | undefined;
      question: string | undefined;
      action: string | undefined;
      "review-below": string | undefined;
      "group-by": string | undefined;
      "row-key": string | undefined;
      accents: string | undefined;
      "client-max": string | undefined;
      "views-storage": string | undefined;
      filename: string | undefined;
      height: string | undefined;
      locale: string | undefined;
      heading: string | undefined;
      description: string | undefined;
      mode: DialogMode | ScanMode | GuardMode | ReviewMode | ChecklistMode | undefined;
      size: DialogSize | string | undefined;
      url: string | undefined;
      hold: string | undefined;
      for: string | undefined;
      menu: string | undefined;
      account: string | undefined;
      current: string | undefined;
      status: AccountStatus | undefined;
      "apply-locale": string | undefined;
      appearance: string | undefined;
      "expires-at": string | undefined;
      "warn-before": string | undefined;
      "view-as-source": string | undefined;
      "logout-url": string | undefined;
      "logout-method": string | undefined;
      "logout-csrf": string | undefined;
      "logout-csrf-field": string | undefined;
      sync: string | undefined;
      agent: string | undefined;
      hotkey: string | undefined;
      limit: string | undefined;
      show: string | undefined;
      storage: string | undefined;
      undo: string | undefined;
      layout: string | undefined;
      format: NumberFormat | undefined;
      currency: string | undefined;
      decimals: string | undefined;
      min: string | undefined;
      max: string | undefined;
      step: string | undefined;
      align: NumberAlign | undefined;
      start: string | undefined;
      end: string | undefined;
      phrase: string | undefined;
      compare: string | undefined;
      today: string | undefined;
      "fiscal-start": string | undefined;
      "week-start": string | undefined;
    }
    interface ExplicitBoolAttributes {
      sticky: boolean;
      editing: boolean;
      notify: boolean;
      always: boolean;
      hold: boolean;
      "ask-name": boolean;
      "ask-id": boolean;
      geo: boolean;
      auto: boolean;
      search: boolean;
      searchable: boolean;
      autostart: boolean;
      muted: boolean;
      collapsed: boolean;
      collapsible: boolean;
      "auto-collapse": boolean;
      busy: boolean;
      "icon-only": boolean;
      "new-tab": boolean;
      download: boolean;
      disabled: boolean;
      multiple: boolean;
      required: boolean;
      clearable: boolean;
      avatar: boolean;
      feedback: boolean;
      "facets-open": boolean;
      persistent: boolean;
      selectable: boolean;
      "require-reason": boolean;
      "require-review": boolean;
      echo: boolean;
      words: boolean;
      readonly: boolean;
    }
    interface CustomEvents {
      "nx-jobs-change": CustomEvent<{ jobs: Job[] }>;
      "nx-jobs-done": CustomEvent<{ job: Job }>;
      "nx-jobs-error": CustomEvent<JobsErrorDetail>;
      "nx-recurrence-error": CustomEvent<RecurrenceErrorDetail>;
      "nx-checklist-change": CustomEvent<ChecklistChangeDetail>;
      "nx-checklist-complete": CustomEvent<ChecklistCompleteDetail>;
      "nx-checklist-open": CustomEvent<ChecklistOpenDetail>;
      "nx-checklist-error": CustomEvent<ChecklistErrorDetail>;
      "nx-thread-post": CustomEvent<ThreadPostDetail>;
      "nx-thread-change": CustomEvent<{ comments: ThreadComment[] }>;
      "nx-thread-mention": CustomEvent<ThreadMentionDetail>;
      "nx-thread-error": CustomEvent<ThreadErrorDetail>;
      "nx-voice-start": CustomEvent<Record<string, never>>;
      "nx-voice-partial": CustomEvent<{ text: string }>;
      "nx-voice-text": CustomEvent<VoiceTextDetail>;
      "nx-voice-end": CustomEvent<VoiceEndDetail>;
      "nx-voice-error": CustomEvent<VoiceErrorDetail>;
      "nx-voice-unavailable": CustomEvent<Record<string, never>>;
      "nx-review-open": CustomEvent<ReviewOpenDetail>;
      "nx-review-confirm": CustomEvent<ReviewConfirmDetail>;
      "nx-review-cancel": CustomEvent<{ changes: ReviewChange[] }>;
      "nx-review-dirty": CustomEvent<ReviewDirtyDetail>;
      "nx-planner-change": CustomEvent<PlannerChangeDetail>;
      "nx-planner-create": CustomEvent<PlannerCreateDetail>;
      "nx-planner-delete": CustomEvent<PlannerDeleteDetail>;
      "nx-planner-select": CustomEvent<{ booking: PlannerBooking }>;
      "nx-planner-range": CustomEvent<PlannerRangeDetail>;
      "nx-signature-change": CustomEvent<{ empty: boolean }>;
      "nx-signature-done": CustomEvent<SignatureDoneDetail>;
      "nx-print-paginate": CustomEvent<PrintPaginateDetail>;
      "nx-print-before": CustomEvent<PrintPaginateDetail>;
      "nx-print-after": CustomEvent<PrintPaginateDetail>;
      "nx-launcher-select": CustomEvent<LauncherSelectDetail>;
      "nx-cards-open": CustomEvent<CardsOpenDetail>;
      "nx-cards-action": CustomEvent<CardsActionDetail>;
      "nx-cards-level": CustomEvent<{ level: CardsLevel }>;
      "nx-org-focus": CustomEvent<OrgFocusDetail>;
      "nx-award-advise": CustomEvent<AwardAdviseDetail>;
      "nx-award-change": CustomEvent<AwardChangeDetail>;
      "nx-award-submit": CustomEvent<AwardSubmitDetail>;
      "nx-account-switch": CustomEvent<AccountSwitchDetail>;
      "nx-account-status": CustomEvent<AccountStatusDetail>;
      "nx-account-theme": CustomEvent<AccountThemeDetail>;
      "nx-account-locale": CustomEvent<{ locale: string }>;
      "nx-account-select": CustomEvent<{ id: string }>;
      "nx-account-view-as": CustomEvent<AccountViewAsDetail>;
      "nx-account-extend": CustomEvent<{ session: AccountSession | null }>;
      "nx-account-expired": CustomEvent<{ expiresAt: number | null }>;
      "nx-account-logout": CustomEvent<AccountLogoutDetail>;
      "nx-handoff-state": CustomEvent<{ state: HandoffState }>;
      "nx-handoff-item": CustomEvent<HandoffItemDetail>;
      "nx-handoff-done": CustomEvent<HandoffDoneDetail>;
      "nx-handoff-error": CustomEvent<{ message: string }>;
      "nx-guard-warn": CustomEvent<{ field: string; finding: GuardFinding }>;
      "nx-guard-fix": CustomEvent<{ field: string; from: number | string | null; to: number | string }>;
      "nx-guard-ack": CustomEvent<{ field: string; value: number | string | null }>;
      "nx-guard-block": CustomEvent<{ findings: GuardFinding[] }>;
      "nx-keytips-activate": CustomEvent<KeytipDetail>;
      "nx-import-parsed": CustomEvent<ImportParsedDetail>;
      "nx-import-mapped": CustomEvent<ImportMappedDetail>;
      "nx-import-done": CustomEvent<ImportDoneDetail>;
      "nx-import-error": CustomEvent<ImportErrorDetail>;
      "nx-sync-done": CustomEvent<{ op: SyncOp; data: unknown }>;
      "nx-sync-change": CustomEvent<SyncChangeDetail>;
      "nx-sync-auth": CustomEvent<{ op: SyncOp }>;
      "nx-scan-error": CustomEvent<{ problem: ScanProblem }>;
      "nx-scan-count": CustomEvent<ScanCountDetail>;
      "nx-scan-read": CustomEvent<ScanDetail>;
      "nx-trend-toggle": CustomEvent<{ id: string; visible: boolean }>;
      "nx-trend-why": CustomEvent<TrendWhyDetail>;
      "nx-what-if-change": CustomEvent<WhatIfChangeDetail>;
      "nx-what-if-save": CustomEvent<WhatIfSaveDetail>;
      "nx-what-if-compute": CustomEvent<WhatIfComputeDetail>;
      "nx-presence-local": CustomEvent<PresenceEvent>;
      "nx-presence-change": CustomEvent<{ users: PresenceState[] }>;
      "nx-sidemenu-select": CustomEvent<SelectDetail>;
      "nx-sidemenu-toggle": CustomEvent<ToggleDetail>;
      "nx-open-change": CustomEvent<OpenChangeDetail>;
      "nx-button-done": CustomEvent<DoneDetail>;
      "nx-select-change": CustomEvent<SelectChangeDetail>;
      "nx-number-change": CustomEvent<NumberChangeDetail>;
      "nx-date-range-change": CustomEvent<DateRangeChangeDetail>;
      "nx-recurrence-change": CustomEvent<RecurrenceChangeDetail>;
      "nx-ai-answer-done": CustomEvent<AiDoneDetail>;
      "nx-ai-answer-action": CustomEvent<AiActionDetail>;
      "nx-ai-answer-feedback": CustomEvent<AiFeedbackDetail>;
      "nx-doc-capture-done": CustomEvent<{ values: CaptureValues; pending: string[] }>;
      "nx-doc-capture-submit": CustomEvent<CaptureSubmitDetail>;
      "nx-grid-filter": CustomEvent<GridFilterDetail>;
      "nx-grid-change": CustomEvent<{ changes: GridChange[]; source: GridChangeSource }>;
      "nx-grid-columns": CustomEvent<{ columns: GridColumn[] }>;
      "nx-dialog-close": CustomEvent<DialogCloseDetail>;
      "nx-dialog-nav": CustomEvent<DialogNavDetail>;
      "nx-dialog-action": CustomEvent<DialogActionDetail>;
      "nx-notice-action": CustomEvent<NoticeActionDetail>;
      "nx-fields-action": CustomEvent<FieldsActionDetail>;
      "nx-tabs-change": CustomEvent<TabsChangeDetail>;
      "nx-breadcrumb-navigate": CustomEvent<BreadcrumbNavigateDetail>;
      "nx-breadcrumb-expand": CustomEvent<BreadcrumbExpandDetail>;
      "nx-grid-selection": CustomEvent<{ ids: string[]; count: number }>;
      "nx-agent-tool": CustomEvent<AgentToolDetail>;
      "nx-agent-state": CustomEvent<{ state: unknown }>;
      "nx-agent-event": CustomEvent<AguiEvent>;
      "nx-grid-open": CustomEvent<{ id: string; row: GridRow; key: string; origin: HTMLElement | null }>;
      "nx-grid-action": CustomEvent<GridActionDetail>;
      "nx-grid-views": CustomEvent<{ views: GridSavedView[] }>;
      "nx-grid-error": CustomEvent<GridErrorDetail>;
      "nx-grid-export": CustomEvent<GridExportDetail>;
      "nx-command-select": CustomEvent<CommandSelectDetail>;
      "nx-command-ask": CustomEvent<{ query: string }>;
      "nx-inbox-decide": CustomEvent<InboxDecisionDetail>;
      "nx-inbox-commit": CustomEvent<InboxDecisionDetail>;
      "nx-inbox-undo": CustomEvent<InboxDecisionDetail>;
      "nx-inbox-active": CustomEvent<{ id: string; item: InboxItem }>;
      "nx-survey-submit": CustomEvent<SurveySubmitDetail>;
      "nx-history-revert": CustomEvent<HistoryRevertDetail>;
      "nx-history-commit": CustomEvent<HistoryCommitDetail>;
      "nx-history-comment": CustomEvent<{ text: string }>;
      "nx-history-travel": CustomEvent<{ id: string | null; record: Record<string, HistoryValue> }>;
      "nx-kanban-move": CustomEvent<KanbanMoveDetail>;
      "nx-kanban-commit": CustomEvent<KanbanMoveDetail>;
      "nx-kanban-undo": CustomEvent<KanbanMoveDetail>;
      "nx-kanban-add": CustomEvent<{ column: string }>;
      "nx-kanban-open": CustomEvent<{ card: KanbanCard }>;
      "nx-survey-change": CustomEvent<{ id: string; value: unknown; answers: SurveyAnswers }>;
      "nx-paste-fill-start": CustomEvent<{ text: string }>;
      "nx-paste-fill-done": CustomEvent<PasteFillDoneDetail>;
      "nx-paste-fill-undo": CustomEvent<{ values: Record<string, string> }>;
    }
    interface IntrinsicElements {
      "nx-jobs": HTMLAttributes<NxJobs>;
      "nx-recurrence": HTMLAttributes<NxRecurrence>;
      "nx-checklist": HTMLAttributes<NxChecklist>;
      "nx-thread": HTMLAttributes<NxThread>;
      "nx-voice": HTMLAttributes<NxVoice>;
      "nx-review": HTMLAttributes<NxReview>;
      "nx-planner": HTMLAttributes<NxPlanner>;
      "nx-signature": HTMLAttributes<NxSignature>;
      "nx-print": HTMLAttributes<NxPrint> & { heading?: string };
      "nx-badge": HTMLAttributes<NxBadge>;
      "nx-notice": HTMLAttributes<NxNotice>;
      "nx-fields": HTMLAttributes<NxFields>;
      "nx-tabs": HTMLAttributes<NxTabs>;
      "nx-breadcrumb": HTMLAttributes<NxBreadcrumb>;
      "nx-org": HTMLAttributes<NxOrg> & { source?: string };
      "nx-award": HTMLAttributes<NxAward> & { heading?: string; endpoint?: string };
      "nx-account": HTMLAttributes<NxAccount>;
      "nx-launcher": HTMLAttributes<NxLauncher>;
      "nx-cards": HTMLAttributes<NxCards>;
      "nx-handoff": HTMLAttributes<NxHandoff> & { endpoint?: string; for?: string };
      "nx-guard": HTMLAttributes<NxGuard> & { endpoint?: string };
      "nx-import": HTMLAttributes<NxImport> & { endpoint?: string };
      "nx-keytips": HTMLAttributes<NxKeytips>;
      "nx-sync": HTMLAttributes<NxSync> & { ping?: string };
      "nx-scan": HTMLAttributes<NxScan> & { source?: string };
      "nx-trend": HTMLAttributes<NxTrend> & { heading?: string };
      "nx-what-if": HTMLAttributes<NxWhatIf> & { heading?: string; endpoint?: string };
      "nx-presence": HTMLAttributes<NxPresence> & { channel?: string; source?: string; for?: string };
      "nx-sidemenu": HTMLAttributes<NxSidemenu> & { active?: string };
      "nx-button": HTMLAttributes<NxButton> & { label?: string; icon?: string; variant?: ButtonVariant };
      "nx-select": HTMLAttributes<NxSelect> & { label?: string; placeholder?: string };
      "nx-ai-answer": HTMLAttributes<NxAiAnswer> & { endpoint?: string; placeholder?: string };
      "nx-doc-capture": HTMLAttributes<NxDocCapture> & { endpoint?: string };
      "nx-grid": HTMLAttributes<NxGrid> & { source?: string };
      "nx-dialog": HTMLAttributes<NxDialog> & { heading?: string };
      "nx-agent": HTMLAttributes<NxAgent> & { endpoint?: string };
      "nx-command": HTMLAttributes<NxCommand>;
      "nx-explain": HTMLAttributes<NxExplain> & { endpoint?: string };
      "nx-inbox": HTMLAttributes<NxInbox> & { heading?: string };
      "nx-survey": HTMLAttributes<NxSurvey> & { heading?: string };
      "nx-number": HTMLAttributes<NxNumber> & { label?: string; placeholder?: string };
      "nx-kanban": HTMLAttributes<NxKanban> & { heading?: string };
      "nx-date-range": HTMLAttributes<NxDateRange> & { label?: string; placeholder?: string };
      "nx-history": HTMLAttributes<NxHistory> & { heading?: string; source?: string };
      "nx-paste-fill": HTMLAttributes<NxPasteFill> & { endpoint?: string; for?: string };
    }
  }
}
