// CSS de la librería: resuelve los @import, baja el anidamiento para Safari 17.0 y minifica.
import { build } from "esbuild";

const target = ["chrome114", "firefox125", "safari17"];
const entries = {
  "nx32-elements": "src/styles/nx32-elements.css",
  tokens: "src/styles/tokens.css",
  palettes: "src/styles/palettes.css",
  sidemenu: "src/components/sidemenu/sidemenu.css",
  button: "src/components/button/button.css",
  select: "src/components/select/select.css",
  ai: "src/components/ai/ai-answer.css",
  capture: "src/components/capture/doc-capture.css",
  grid: "src/components/grid/grid.css",
  dialog: "src/components/dialog/dialog.css",
  confirm: "src/components/confirm/confirm.css",
  toast: "src/components/toast/toast.css",
  agent: "src/components/agent/agent.css",
  command: "src/components/command/command.css",
  explain: "src/components/explain/explain.css",
  inbox: "src/components/inbox/inbox.css",
  survey: "src/components/survey/survey.css",
  tour: "src/components/tour/tour.css",
  "sync": "src/components/sync/sync.css",
  "scan": "src/components/scan/scan.css",
  "trend": "src/components/trend/trend.css",
  "what-if": "src/components/what-if/what-if.css",
  "presence": "src/components/presence/presence.css",
  "paste-fill": "src/components/paste-fill/paste-fill.css",
  "date-range": "src/components/date-range/date-range.css",
  "history": "src/components/history/history.css",
  "kanban": "src/components/kanban/kanban.css",
  "number": "src/components/number/number.css",
  "jobs": "src/components/jobs/jobs.css",
  "recurrence": "src/components/recurrence/recurrence.css",
  "checklist": "src/components/checklist/checklist.css",
  "thread": "src/components/thread/thread.css",
  "voice": "src/components/voice/voice.css",
  "review": "src/components/review/review.css",
  "planner": "src/components/planner/planner.css",
  "signature": "src/components/signature/signature.css",
  "print": "src/components/print/print.css",
  "badge": "src/components/badge/badge.css",
  "notice": "src/components/notice/notice.css",
  "fields": "src/components/fields/fields.css",
  "field": "src/components/field/field.css",
  "form": "src/components/form/form.css",
  "tabs": "src/components/tabs/tabs.css",
  "breadcrumb": "src/components/breadcrumb/breadcrumb.css",
  "org": "src/components/org/org.css",
  "account": "src/components/account/account.css",
  "launcher": "src/components/launcher/launcher.css",
  "timeline": "src/components/timeline/timeline.css",
  "intent": "src/components/intent/intent.css",
  "tracker": "src/components/tracker/tracker.css",
  "stats": "src/components/stats/stats.css",
  "cards": "src/components/cards/cards.css",
  "handoff": "src/components/handoff/handoff.css",
  "award": "src/components/award/award.css",
  "guard": "src/components/guard/guard.css",
  "import": "src/components/import/import.css",
  "keytips": "src/components/keytips/keytips.css",
};

await build({
  entryPoints: entries,
  outdir: "dist",
  bundle: true,
  minify: true,
  target,
  logLevel: "warning",
});
console.log("css →", Object.keys(entries).map((k) => `dist/${k}.css`).join(", "));
