export * from "./components/sidemenu/index";
export * from "./components/button/index";
export * from "./components/select/index";
export * from "./components/ai/index";
export * from "./components/capture/index";
export * from "./components/grid/index";
export * from "./components/dialog/index";
export * from "./components/confirm/index";
export * from "./components/toast/index";
export * from "./components/agent/index";
export * from "./components/command/index";
export * from "./components/explain/index";
export * from "./components/inbox/index";
export * from "./components/survey/index";
export * from "./components/tour/index";
export * from "./components/sync/index";
export * from "./components/scan/index";
export * from "./components/trend/index";
export * from "./components/what-if/index";
export * from "./components/presence/index";
export * from "./components/paste-fill/index";
export * from "./components/date-range/index";
export * from "./components/history/index";
export * from "./components/kanban/index";
export * from "./components/number/index";
export * from "./components/jobs/index";
export * from "./components/recurrence/index";
export { parseRecurrence } from "./components/recurrence/parse";
export * from "./components/checklist/index";
export * from "./components/thread/index";
export * from "./components/voice/index";
export { applyDictation, parseDictation } from "./components/voice/voice-text";
export { VOICE_MIMES, parseVoiceLine, pickVoiceMime, voiceFileName } from "./components/voice/voice-server";
export * from "./components/review/index";
export * from "./components/planner/index";
export * from "./components/signature/index";
export * from "./components/print/index";
export * from "./components/badge/index";
export * from "./components/notice/index";
export * from "./components/fields/index";
export * from "./components/field/index";
export * from "./components/form/index";
export * from "./components/tabs/index";
export * from "./components/breadcrumb/index";
export * from "./components/org/index";
export * from "./components/account/index";
export * from "./components/launcher/index";
export * from "./components/cards/index";
export * from "./components/handoff/index";
export * from "./components/award/index";
export * from "./components/guard/index";
export * from "./components/import/index";
export * from "./components/keytips/index";
// Lo mismo que `nx32-elements/core`, pero desde sus archivos: reexportar el módulo de la subruta
// haría que dist/index.js lo importe «sin efectos» y esbuild avisaría en cada app.
export { registerIcons, hasIcon } from "./core/icons";
export { nxFormat, resolveLocale, canonicalLocale, type NxFormat, type MoneyLike } from "./core/locale";
export { allowOrigins, safeEndpoint, safeHref } from "./core/dom";
export { nxSupported, type NxSupport, type NxFeature } from "./core/support";
